# Used in production setup on a k8s/openshift cluster

app:
  baseUrl: https://service-catalog.operate-first.cloud

backend:
  baseUrl: https://service-catalog.operate-first.cloud
  database:
    client: pg
    connection:
      host: ${host}
      user: ${user}
      password: ${password}
      port: ${port}
      # https://node-postgres.com/features/ssl
      # you can set the sslmode configuration option via the `PGSSLMODE` environment variable
      # see https://www.postgresql.org/docs/current/libpq-ssl.html Table 33.1. SSL Mode Descriptions (e.g. require)
      ssl:
        ca:
          $file: /mnt/certs/ca.crt
  cors:
    origin: https://service-catalog.operate-first.cloud

techdocs:
  builder: "external"
  generator:
    runIn: "local"
  publisher:
    type: "awsS3"
    awsS3:
      bucketName: ${BUCKET_NAME}
      region: ${BUKCET_REGION}
      endpoint: https://s3-openshift-storage.apps.smaug.na.operate-first.cloud
      s3ForcePathStyle: true
      credentials:
        accessKeyId: ${AWS_ACCESS_KEY_ID}
        secretAccessKey: ${AWS_SECRET_ACCESS_KEY}

auth:
  environment: production
  providers:
    github:
      production:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}

catalog:
  locations:
    - type: url
      target: https://github.com/operate-first/apps/blob/master/service-catalog/all.yaml

kubernetes:
  serviceLocatorMethod:
    type: "multiTenant"
  clusterLocatorMethods:
    - type: "config"
      clusters:
        - url: https://api.smaug.na.operate-first.cloud:6443
          name: smaug
          authProvider: "serviceAccount"
          skipTLSVerify: false
          skipMetricsLookup: false
          serviceAccountToken: ${moc_smaug_token}
          dashboardUrl: https://console-openshift-console.apps.smaug.na.operate-first.cloud
          dashboardApp: openshift
        - url: https://api.moc-infra.massopen.cloud:6443
          name: infra
          authProvider: 'serviceAccount'
          skipTLSVerify: false
          skipMetricsLookup: false
          serviceAccountToken: ${moc_infra_token}
          dashboardUrl: https://console-openshift-console.apps.moc-infra.massopen.cloud
          dashboardApp: openshift
        - url: https://api.curator.massopen.cloud:6443
          name: curator
          authProvider: 'serviceAccount'
          skipTLSVerify: false
          skipMetricsLookup: false
          serviceAccountToken: ${moc_curator_token}
          dashboardUrl: https://console-openshift-console.apps.curator.massopen.cloud
          dashboardApp: openshift
        - url: https://api.balrog.aws.operate-first.cloud:6443
          name: balrog
          authProvider: 'serviceAccount'
          skipTLSVerify: false
          skipMetricsLookup: false
          serviceAccountToken: ${emea_balrog_token}
          dashboardUrl: https://console-openshift-console.apps.balrog.aws.operate-first.cloud
          dashboardApp: openshift
        - url: https://api.odh-cl1.apps.os-climate.org:6443
          name: osc-cl1
          authProvider: 'serviceAccount'
          skipTLSVerify: false
          skipMetricsLookup: false
          serviceAccountToken: ${osc_osc-cl1_token}
          dashboardUrl: https://console-openshift-console.apps.odh-cl1.apps.os-climate.org
          dashboardApp: openshift
        - url: https://api.odh-cl2.apps.os-climate.org:6443
          name: osc-cl2
          authProvider: 'serviceAccount'
          skipTLSVerify: false
          skipMetricsLookup: false
          serviceAccountToken: ${osc_osc-cl2_token}
          dashboardUrl: https://console-openshift-console.apps.odh-cl2.apps.os-climate.org
          dashboardApp: openshift

clusterStatus:
  acmCluster: 'infra'
