# Used in local develompment setup

app:
  baseUrl: http://localhost:3000

backend:
  baseUrl: http://localhost:7007
  cors:
    origin: http://localhost:3000
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ":memory:"

catalog:
  locations:
    - type: file
      target: ../../${CATALOG_LOCAL_PATH}
    #  Uncomment to use defintions files from apps repo
    # - type: url
    #   target: https://github.com/operate-first/apps/blob/master/service-catalog/all.yaml

auth:
  environment: development
  providers:
    github:
      development:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}

kubernetes:
  serviceLocatorMethod:
    type: "multiTenant"
  clusterLocatorMethods:
    - type: "config"
      clusters:
        # This is using kubectl proxy which is started in the yarn dev script
        - url: http://localhost:8001
          name: dev-cluster
          authProvider: "serviceAccount"
          skipTLSVerify: false
          skipMetricsLookup: false
          # If you are not signed in to your cluster, use a Service Account token
          # serviceAccountToken: ${SERVICE_ACCOUNT_TOKEN}
          # Optional values
          # dashboardUrl: <dashboard_url>
          # dashboardApp: <dashboard_type>  # Supported dashboards: standard, rancher, openshift, gke, aks, eks

clusterStatus:
  acmCluster: 'dev-cluster'
