# Used in dev setup on a k8s/openshift cluster

app:
  baseUrl: <url>

backend:
  baseUrl: <url>
  database:
    client: pg
    connection:
      host: ${host}
      user: ${user}
      password: ${password}
      port: ${port}
      # https://node-postgres.com/features/ssl
      # you can set the sslmode configuration option via the `PGSSLMODE` environment variable
      # see https://www.postgresql.org/docs/current/libpq-ssl.html Table 33.1. SSL Mode Descriptions (e.g. require)
      ssl:
        ca:
          $file: /mnt/certs/ca.crt
  cors:
    origin: <url>

catalog:
  locations:
    - type: url
      target: https://github.com/operate-first/apps/blob/master/service-catalog/all.yaml

kubernetes:
  serviceLocatorMethod:
    type: "multiTenant"
  clusterLocatorMethods:
    - type: "config"
      clusters:
        - url: https://openshift.default.svc.cluster.local
          name: dev-cluster
          authProvider: "serviceAccount"
          skipTLSVerify: true
          skipMetricsLookup: false
          # Uncomment this if you want to use a different url other then the local one
          # for local cluster you don't need to provide service account token
          # serviceAccountToken: ${SERVICE_ACCOUNT_TOKEN}
          # Optional values
          # dashboardUrl: <dashboard_url>
          # dashboardApp: <dashboard_type>  # Supported dashboards: standard, rancher, openshift, gke, aks, eks

clusterStatus:
  acmCluster: 'dev-cluster'
